### PR TITLE
attempt to upgrade to Lucene 5.1 (please view todos)

### PR DESCRIPTION
**Pull request by acmeguy**
Hi,

Can someone please review this and run tests. It's an attempt to update the Lucene plugin to 5.1.
Perhaps the 4.6 version is required but I'm hoping a, long overdue, update to 5.1 is in order.

Best regards,
 -Stefan

### CODE REVIEW

**Comment by acmeguy** [comment]
I have addition contributions that could benefit from this upgrade. I just want to ask if you think this upgrade can be done without causing problems regarding the upgrade process and backwards compatibility? (I think Lucene 5.1 will read the old format if the correct cars are available to read the old format)

**Comment by lvca** [comment]
@robfrank WDYT?

**Comment by robfrank** [comment]
@acmeguy Lucene is always compatible with previous versions, so 5.x opens 4.x indicies without any problem. After the first write with 5.x the index is converted to the new lucene internal format and can't be opened by previous versions, so you can't open a lucene 5.x with 4.x.

**Comment by lvca** [comment]
So WDYT @maggiolo00 or @robfrank about taking a look at this PR? I'm ok on upgrading to a more recent version of Lucene, since we have one pretty old

**Comment by robfrank** [comment]
@lvca do you want this upgrade for 2.2? Or it is better to wait 3.0?

**Comment by lvca** [comment]
2.2 could be ok, so we still have at least 3 weeks for the first RC and then all the time during RC till the final one (2-3 weeks later?)

**Comment by robfrank** [comment]
Ok, when  @maggiolo00 will finalize the ongoing refactor I'll take in charge of updating to 5.x

**Comment by acmeguy** [comment]
thank you guys. I will be contributing other Lucene related things soon that I trust you will like. Today it's a bit AS specific but with some hours I can take what we have done and make it general (see post on google groups)

**Comment by robfrank** [comment]
We prefer to merge on develop, so I'm doing this work, with lucene 5.2 version, on develop branch right now. Thank you very much for your work, any future PR will be appreciated.

**Pull request closed without merging**
